#!/usr/bin/env bash
# .windsurf/validate.sh — generated by windsurf-bootstrap.
# Single source of truth for the quality gate. Called by:
#   - .windsurf/hooks.json (post_cascade_response):  bash .windsurf/validate.sh fast
#   - /implement, /test, /review workflows:           bash .windsurf/validate.sh full
# Usage: validate.sh [fast|full]   (default: fast = lint + typecheck; full also runs tests)
#
# GENERATOR: fill {{...}} with the detected commands; delete any step the repo lacks.
# For commands containing pipes/&&/redirection, wrap them in a function instead of passing
# them straight to `step` (which runs its args directly).
set -uo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

MODE="${1:-fast}"

# Stay quiet on responses that didn't touch the working tree (answers, planning, etc.).
if [ -z "$(git status --porcelain 2>/dev/null)" ]; then
  echo "validate: no working-tree changes — skipping ($MODE)."
  exit 0
fi

fail=0
step() { local name="$1"; shift; echo; echo "── $name"; "$@" || { echo "✗ $name failed"; fail=1; }; }

step "lint"      {{LINT_CMD}}
# GENERATOR: keep the next line only if the repo has a typecheck step; else delete the whole line.
step "typecheck" {{TYPECHECK_CMD}}
if [ "$MODE" = "full" ]; then
  step "test"    {{TEST_CMD}}
fi

echo
if [ "$fail" -eq 0 ]; then echo "✓ validate ($MODE) passed"; else echo "✗ validate ($MODE) found issues"; fi
exit "$fail"
